### ISSUE TITLE
Install guide neglects to mention setting permissions for KVM device

### ISSUE THREAD

**Issue by jethrogb** [enarx/website#140]
The [install guide](https://enarx.dev/docs/Install) has instructions for setting the permissions on the SEV device, but similar permissions are needed on the KVM device.

I would've filed a PR but couldn't find the source.

**Comment by rjzak** [comment]
Oddly enough, I can't find the install page either. @nickvidal?

**Comment by nickvidal** [comment]
That's a good question @jethrogb 

The installation guide lives in the Enarx project itself because the instructions are tested.

We would welcome your PR here:

https://github.com/enarx/enarx/blob/main/docs/Install.md

Thanks!
